type AmountTitleObj = {
  amount: number;
  title: string;
};

type LocationObj = {
  longitude: number;
  latitude: number;
  altitude?: number;
  timestamp?: number;
  city?: string;
  state?: string;
  country?: string;
  postalCode?: string;
  district?: string;
  isoCountryCode?: string;
};

interface bubbleDataItem {
  y: number;
  x?: number;
  r?: number;
  label?: string;
  labelComponent?: Function;
  labelTextStyle?: StyleProp<TextStyle>;
  secondaryLabel?: string;
  secondaryLabelComponent?: Function;
  secondaryLabelTextStyle?: StyleProp<TextStyle>;
  bubbleText?: string;
  textShiftX?: number;
  textShiftY?: number;
  spacing?: number;
  hideBubble?: boolean;
  bubbleHeight?: number;
  bubbleWidth?: number;
  bubbleColor?: string;
  bubbleShape?: string;
  customBubble?: Function;
  stripHeight?: number;
  stripWidth?: number;
  stripColor?: ColorValue | string | any;
  stripOpacity?: number;
  stripStrokeDashArray?: number[];
  focusedBubbleShape?: string;
  focusedBubbleWidth?: number;
  focusedBubbleHeight?: number;
  focusedBubbleColor?: ColorValue | string | any;
  focusedBubbleRadius?: number;
  focusedCustomBubble?: Function;
  labelComponent?: Function;
  focusedLabelComponent?: Function;
  labelWidth?: number;
  labelShiftX?: number;
  labelShiftY?: number;
  showStrip?: boolean;
  showVerticalLine?: boolean;
  verticalLineHeight?: number;
  verticalLineUptoBubble?: boolean;
  verticalLineColor?: ColorValue;
  verticalLineThickness?: number;
  verticalLineStrokeDashArray?: number[];
  verticalLineSpacing?: number;
  verticalLineStrokeLinecap?: Linecap;
  pointerShiftX?: number;
  pointerShiftY?: number;
  onPress?: Function;
  onContextMenu?: Function;
  onMouseEnter?: Function;
  onMouseLeave?: Function;
  showXAxisIndex?: boolean;
  hidePointer?: boolean;
  borderWidth?: number;
  borderColor?: ColorValue;
  borderOpacity?: number;
  opacity?: number;
}
