#!/bin/bash

# Exit immediately if any command fails
set -e

# 1. Ensure you are starting with the latest main branch
git checkout main
git pull origin main

# 2. Switch to the build branch
git checkout build

# 3. Merge main into build to keep it up to date
git merge main -m "chore: merge main into build"

# 4. Run the Node.js script (Takes argument 1, defaults to build.js)
JS_FILE=${1:-version-update.js}
echo "Running Node script: $JS_FILE"
node "$JS_FILE"

# 5. Stage and commit any changes produced by the script
git add .

# Only commit if there are actual changes in the git tree
if ! git diff --cached --quiet; then
    git commit -m "chore: run build script and update assets"
else
    echo "No changes generated by the script."
fi

# 6. Push the updated build branch to the remote repository
git push origin build

# 7. Switch back to the main branch
git checkout main

echo "Pipeline complete! Returned to main branch."
